name: Deploy Cassie Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Dependencies
      run: |
        cd cassie-frontend
        npm install
        cd ../cassie-backend
        npm install

    - name: Build Frontend
      run: |
        cd cassie-frontend
        npm run build

    - name: Run Tests
      run: |
        cd cassie-frontend
        npm test --passWithNoTests
        cd ../cassie-backend
        npm test --passWithNoTests

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./cassie-frontend/build 